[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "20.6.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
